proposal: save static memory
earlephilhower/ESP8266SAM pull request #7
Opened 2019-02-25 01:53 UTC by liebman

There are many 256 and 60 byte arrays, about 4k in total, that are only used during "say".  On an ESP8266 that uses enough memory to prevent using SSL.  This, hack at the moment, shows that one can dynamically allocate these when needed and keep memory free for https requests as long as they are not both used at the same time.  Thoughts?

2019-02-25 16:43 UTC, earlephilhower requested changes
Thanks!

Looks like a good way of doing it.  I'd be happy to merge if a couple tweaks were made:
. Make the SAMData a member of the class, seems like logically it should be there
. Get rid of the `#if SAMDATA` and just replace it always.
. How about making `::say()` return a bool, and `false` when it's OOM, OTW `true`?  That way we can inform the main code if they care enough to check

Hope that makes sense.  I'd just like to minimize the potential combos to break, and it seems like a good improvement.

-EFP3

2019-02-25 23:31 UTC, liebman commented
> . Make the SAMData a member of the class, seems like logically it should be there

If its a class member it won't be accessible from the C code.

> . Get rid of the `#if SAMDATA` and just replace it always.

Will do.

> . How about making `::say()` return a bool, and `false` when it's OOM, OTW `true`? That way we can inform the main code if they care enough to check

Good idea.

2019-02-25 23:34 UTC, earlephilhower commented
> > . Make the SAMData a member of the class, seems like logically it should be there

> If its a class member it won't be accessible from the C code.

Fair enough, I stand corrected. :)

2019-03-02 16:44 UTC, liebman commented
Ok - your suggestions have been implemented.

2019-03-09 18:27 UTC, liebman commented
@earlephilhower any more changes needed?

2019-03-09 18:35 UTC, merged

2019-03-09 18:36 UTC, earlephilhower commented
Thanks for the reminder.  I've been busy preparing for an industry trade show and not looking at the projects much this month.